Add initialize flag to v1/shell
ChameleonCloud/python-heatclient pull request #1
Opened 2019-01-03 22:43 UTC by jakecoll

2019-01-03 22:45 UTC, diurnalist approved these changes
LGTM

2019-01-07 15:23 UTC, priteau requested changes

2019-01-07 15:23 UTC, priteau commented on heatclient/v1/shell.py
> +           help=_('Only initialize stack and do not allocate resrouces.'))
s/resrouces/resources/

2019-01-09 19:30 UTC, jakecoll commented on heatclient/v1/shell.py
> +           help=_('Only initialize stack and do not allocate resrouces.'))
fixed type

2019-01-09 19:30 UTC, jakecoll commented on heatclient/v1/shell.py
> +           help=_('Only initialize stack and do not allocate resrouces.'))
*typo

2019-01-09 19:31 UTC, merged